# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tinyatom}
  s.version = "0.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew M. Boedicker"]
  s.date = %q{2010-11-27}
  s.description = %q{Small and easy to use ruby Atom feed generator.}
  s.email = %q{matthewm@boedicker.org}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "COPYING",
    "README.textile",
    "Rakefile",
    "VERSION",
    "lib/tinyatom.rb",
    "lib/tinyatom/feed.rb",
    "lib/tinyatom/uri_domain.rb",
    "tinyatom.gemspec"
  ]
  s.homepage = %q{http://github.com/mmb/tinyatom}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Small and easy to use ruby Atom feed generator.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<builder>, ["~> 2.0"])
      s.add_runtime_dependency(%q<public_suffix_service>, ["~> 0.0"])
    else
      s.add_dependency(%q<builder>, ["~> 2.0"])
      s.add_dependency(%q<public_suffix_service>, ["~> 0.0"])
    end
  else
    s.add_dependency(%q<builder>, ["~> 2.0"])
    s.add_dependency(%q<public_suffix_service>, ["~> 0.0"])
  end
end

